### ISSUE TITLE
LICENSE generation change

### ISSUE THREAD

**Issue by solvingj** [sigmoidal/conan-readme-generator#2]
Noticed two items for update on the generators regarding license.  

First, it looks like the generator is currently generating with name `LICENSE.md` instead of just `LICENSE`.  We've been using standard convention of `LICENSE` like the rest of the industry for a long time.  If there's some technological reason to change to `.md`, I'm not opposed to switching.  Please raise an issue for discussion and put it on this board so that it makes it into the refresh project which is rapidly approaching.  
https://github.com/bincrafters/community/projects/7

The other one is that I noticed the text `MIT` at the bottom isn't a link to the `LICENSE.md`.  Rather than fix this, I think we can do better.  I would like to eliminate the license text at the bottom of the Readme, and use the License badges @uilianries has been using at the top of the Readme.  Again, lets raise an issue and put it on the same board above. 

https://gist.github.com/lukas-h/2a5d00690736b4c3a7ba

**Comment by sigmoidal** [comment]
I have "donated" this project to bincrafters: https://github.com/bincrarfters/conan-readme-generator 
So I will be closing this, sorry for the confusion. You should obtain the latest version from that one.

Anyhow, for the scheme I used what Github suggests: https://help.github.com/articles/licensing-a-repository 

The technical advantage is that the license can be markdown-styled, nothing else I guess.

I am indifferent, if the team wants LICENSE instead of LICENSE.md is fine by me. It is also configurable anyway, but I'm all in for good defaults.

**Comment by solvingj** [comment]
Oh, ok sounds good.  i should have known to use the other repo.
